### ISSUE TITLE
Does not work the first time

### ISSUE THREAD

**Issue by hotice** [rbrs/ubuntu-twitch-indicator#12]
The first time you run the indicator and add your Twitch username, it doesn't work, and the following output is displayed in the terminal:

```
$ twitch-indicator 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/twitch-indicator", line 238, in refresh_streams
    self.live_streams = self.tw.fetch_live_streams(self.followed_channels)
  File "/usr/bin/twitch-indicator", line 57, in fetch_live_streams
    self.f = urllib.urlopen("https://api.twitch.tv/kraken/streams?client_id=oe77z9pq798tln7ngil0exwr0mun4hj&channel={0}".format(','.join(self.channels_offset)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 340-342: ordinal not in range(128)
```

After restarting the indicator, it starts working.

**Comment by rolandasb** [comment]
This could be related with #14 - could you try again to see if it resolves your issue?

**Comment by hotice** [comment]
After resetting the twitch-indicator dconf settings and adding my Twitch username, the bug didn't occur with the latest version. So this looks fixed.
